renaudrouas/prep_your_trip

app/controllers/accomodations_controller.rb, app/controllers/diaries_controller.rb, app/controllers/photos_controller.rb, app/controllers/stays_controller.rb, app/controllers/tasks_controller.rb, app/controllers/travels_controller.rb, app/controllers/trips_controller.rb, app/views/diaries/_form.html.erb, app/views/diaries/edit.html.erb, app/views/diaries/index.html.erb, app/views/diaries/new.html.erb, app/views/diaries/show.html.erb, app/views/tasks/_form.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/index.html.erb, app/views/tasks/new.html.erb, app/views/tasks/show.html.erb, app/views/travels/_form.html.erb, app/views/travels/edit.html.erb, app/views/travels/index.html.erb, app/views/travels/new.html.erb, app/views/travels/show.html.erb, config/routes.rb
=> Controllers views

app/controllers/diaries_controller.rb, app/controllers/travels_controller.rb, app/views/diaries/index.html.erb, app/views/diaries/show.html.erb, app/views/stays/edit.html.erb, app/views/stays/index.html.erb, app/views/stays/new.html.erb, app/views/stays/show.html.erb, app/views/travels/show.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb
Navigation links: trips, travels, diaries, tasks
=> Navigation on trips, travels,diaries,tasks

app/models/trip.rb, app/views/pages/_cover-video.html.erb
I added links in HP ( not in navbar) . 
Two differents links depending on 2 situation : 
User log in
User not legged in
=> link added to HP

app/assets/stylesheets/components/_cover-video.scss, app/models/trip.rb
A container was blocking the navbar links in the HP. Now it's working.
=> links in navbar ar now working in HP

app/assets/javascripts/application.js, app/assets/javascripts/caroussel.js, app/controllers/trips_controller.rb, app/models/travel.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/travels/index.html.erb, package.json, yarn.lock
=>  logout is ok

app/controllers/accomodations_controller.rb, app/controllers/trips_controller.rb, app/models/accomodation.rb, app/models/diary.rb, app/views/accomodations/_form.html.erb, app/views/accomodations/index.html.erb, app/views/accomodations/show.html.erb, app/views/trips/show.html.erb
Crud total on accomodations and stays
changed clickable icons link path, add do and "i class"
=> Crud total of accomodation

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Change color navabr

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login-form.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
I clean up the login and sign up page.
=> Modify the login page

app/assets/stylesheets/pages/_diaries.scss, app/assets/stylesheets/pages/_index.scss, app/views/diaries/_form.html.erb, app/views/diaries/new.html.erb, app/views/diaries/show.html.erb
J'ai terminé la vue New diary et show de diary
=> Work on diaries

app/controllers/trips_controller.rb, app/views/trips/show.html.erb
Ok pour météo + info country + vaccins 
PLEASE si vous testez avec un pays il faut soit mettre bolivie soit italia 
Certains pays fonctionnent en anglais et d'autres en français don't know why 💃
=> meteo + vaccin + info pays ok

app/controllers/tasks_controller.rb, app/views/tasks/index.html.erb, app/views/tasks/show.html.erb, app/views/trips/_tasks.html.erb
Checklist navigation
Checklist index.html.erb deleted
=> navigation done

app/views/accomodations/_form.html.erb, app/views/travels/_form.html.erb
=> enum on forms done

app/controllers/accomodations_controller.rb, app/javascript/components/autocomplete.js, app/views/accomodations/_form.html.erb, app/views/accomodations/_map_box.html.erb, app/views/accomodations/index.html.erb, app/views/accomodations/new.html.erb, app/views/travels/_form.html.erb
OK autocomplete marche dans tous les champs + maps ok dans index de transport + hebergement + show trip
=> Update autocomplete new views

app/views/trips/show.html.erb
=> bug in show resolved

app/views/diaries/_form.html.erb
They were a bug on diary because of merging.
I correct it
=> correct a bug

app/controllers/diaries_controller.rb, app/views/trips/_timeline.html.erb, db/schema.rb
=> timline with the right code

app/assets/stylesheets/components/_timeline.scss, app/controllers/diaries_controller.rb, app/controllers/travels_controller.rb, app/controllers/trips_controller.rb, app/views/accomodations/show.html.erb, app/views/diaries/show.html.erb, app/views/travels/show.html.erb, app/views/trips/_timeline.html.erb
Timeline icons: done
Timeline almost clickable
Shows: accomodation, travel, diary, done
=> timeline almost clickable

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_task.scss, app/views/accomodations/index.html.erb, app/views/diaries/index.html.erb, app/views/diaries/show.html.erb, app/views/travels/index.html.erb, app/views/trips/_country-info.html.erb, app/views/trips/index.html.erb, config/locales/en.yml, config/locales/rails.fr.yml
I've change the date 
and change few stuffs on color background
=> Finish polish

app/assets/stylesheets/components/_timeline.scss, app/assets/stylesheets/pages/_trip.scss, app/views/trips/_country-info.html.erb, app/views/trips/_timeline.html.erb, app/views/trips/show.html.erb, db/schema.rb
I updated the time line and some stuffs on country info
=> Work on timeline css

public/404.html, public/422.html, public/500.html
=> customized error html

app/controllers/travels_controller.rb, app/controllers/trips_controller.rb, app/views/accomodations/show.html.erb, db/seeds.rb
=> seeds finished and modified
